#!/bin/bash
env WAYLAND_DISPLAY=wayland-1 
if [[ ! -e $(which wayvnc) ]];then
	notify-send -t 2000 "Please install and Configure [wayvnc]"
fi
if [[ ! -e $HOME/.config/wayvnc/config ]];then
	notify-send -t 2000 "Please Configure [wayvnc]"
fi

declare pid=$(pidof wayvnc)
if [ -z $pid ];then
	notify-send -t 2000 "RemoteDesktop: Started !"
	wayvnc 0.0.0.0 -p 5900
else
	kill $pid
	notify-send -t 2000 "RemoteDesktop: Stoped !"
fi
