#!/bin/bash
sudo pacman -S tigervnc
vncpasswd
chmod 0600 ~/.vnc/passwd
echo "session=hypr" > ~/.vnc/config
echo "geometry=1920x1080" >> ~/.vnc/config
echo "localhost" >> ~/.vnc/config
echo "alwaysshared" >> ~/.vnc/config


## enable vnc server permanently

#echo "Section \"Module\"
#Load \"vnc\"
#EndSection
#
#Section \"Screen\"
#Identifier \"Screen0\"
#Option \"UserPasswdVerifier\" \"VncAuth\"
#Option \"PasswordFile\" \"/root/.vnc/passwd\"
#EndSection" |sudo tee  /etc/X11/xorg.conf.d/10-vnc.conf
